---
- name: prepare workdir
  file:
    path: "{{work_dir}}"
    state: directory

- name: remove old setting file 
  file:
    path: "{{work_dir}}/GreengrassDeviceSetup.config.info"
    state: absent

- name: download deb keyring 
  get_url:
    url: https://d1onfpft10uf5o.cloudfront.net/greengrass-apt/downloads/aws-iot-greengrass-keyring.deb
    dest: "{{work_dir}}/aws-iot-greengrass-keyring.deb"
    mode: u=rw
  
- name: install keyring
  become: true
  shell: >
    dpkg -i {{work_dir}}/aws-iot-greengrass-keyring.deb

- name: Add greengrass repository into sources list
  become: true
  apt_repository:
    repo: deb https://dnw9lb6lzp2d8.cloudfront.net stable main
    state: present
    filename: greengrass

- name: install greengrass
  become: true
  apt:
    update_cache: yes
    name: aws-iot-greengrass-core

- name: download Amazon root CA pem
  become: true
  get_url:
    url: https://www.amazontrust.com/repository/AmazonRootCA1.pem
    dest: "/greengrass/certs/root.ca.pem"
    mode: u=r